#image rate&size
image_loop_duration_: 0.2
size_radio_: 0.5

#color filter mask
tm_iLowH_: 155
tm_iHighH_: 179

tm_iLowS_: 90
tm_iHighS_: 255

tm_iLowV_: 90
tm_iLHighV_: 255

#mavros parameters
tgt_system_id: 3
#fcu_url: "udp://:14540@127.0.0.1:14557"
fcu_url: "/dev/ttyUSB0:921600"
#fcu_url: "/dev/ttyUSB0:57600"
gcs_url: "udp://@localhost"

#TaskManager parameters
self_system_id: 3
tm_outdoor_indoor_flag: 0
tm_takeoff_acc: 0.5
tm_takeoff_hight: 5

# param: value
waypoints:
# ENU frame: x, y z, yaw
# numbers must in x.x format(i.e: 5.0)
- [ 0.0,       -0.0,       5.0,   0.0]
- [ 4.0,       4.0,        5.0,   0.00]
- [ -4.0,      4.0,        5.0,   0.00]
- [ -4.0,      -4.0,       5.0,   0.00]
- [ 4.0,      -4.0,        5.0,   0.00]
- [ 0.0,      -0.0,        5.0,   0.00]
- [ 0.0,      -0.0,        -100.8,   0.00]



